version: "3"

services:
  node:
    image: node:16-alpine
    user: node
    container_name: trybefy
    tty: true
    stdin_open: true
    command: sh
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password123
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306
  db:
    container_name: trybefy_db
    image: mysql:8.0.34
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password123
